services:
  topic-planner:
    container_name: topic-planner
    restart: always
    image: ghcr.io/vmss2009/topic-planner:v1
    ports:
      - "3005:3000"
    networks:
      - hamaralabs-network

networks:
  hamaralabs-network:
    external: true
